// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package caseStudy1.protobuf.AggregatedSensorReading

object AggregatedSensorReadingProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      caseStudy1.protobuf.AggregatedSensorReading.AggregatedSensorReading
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ch1BZ2dyZWdhdGVkU2Vuc29yUmVhZGluZy5wcm90bxITY2FzZVN0dWR5MS5wcm90b2J1ZiKTBAoXQWdncmVnYXRlZFNlbnNvc
  lJlYWRpbmcSKQoIc2Vuc29ySWQYASABKAVCDeI/ChIIc2Vuc29ySWRSCHNlbnNvcklkEkcKEmF2ZXJhZ2VUZW1wZXJhdHVyZRgCI
  AEoAkIX4j8UEhJhdmVyYWdlVGVtcGVyYXR1cmVSEmF2ZXJhZ2VUZW1wZXJhdHVyZRI+Cg9hdmVyYWdlSHVtaWRpdHkYAyABKAJCF
  OI/ERIPYXZlcmFnZUh1bWlkaXR5Ug9hdmVyYWdlSHVtaWRpdHkSRwoSbWluaW11bVRlbXBlcmF0dXJlGAQgASgCQhfiPxQSEm1pb
  mltdW1UZW1wZXJhdHVyZVISbWluaW11bVRlbXBlcmF0dXJlEkcKEm1heGltdW1UZW1wZXJhdHVyZRgFIAEoAkIX4j8UEhJtYXhpb
  XVtVGVtcGVyYXR1cmVSEm1heGltdW1UZW1wZXJhdHVyZRI+Cg9taW5pbXVtSHVtaWRpdHkYBiABKAJCFOI/ERIPbWluaW11bUh1b
  WlkaXR5Ug9taW5pbXVtSHVtaWRpdHkSPgoPbWF4aW11bUh1bWlkaXR5GAcgASgCQhTiPxESD21heGltdW1IdW1pZGl0eVIPbWF4a
  W11bUh1bWlkaXR5EjIKC25vT2ZSZWNvcmRzGAggASgDQhDiPw0SC25vT2ZSZWNvcmRzUgtub09mUmVjb3Jkc2IGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}